#!/usr/bin/env python3
"""Generate a GitLab child-pipeline spec with ONE job per lab (cluster smoke tier).

WHY: the cluster smoke tier used to run every selected workshop sequentially in a
single CI job — one slow lab dragged the whole MR pipeline, and a large workshop set
made one job run for a very long time. This generator turns that into a dynamic child
pipeline: `generate-smoke-spec` (parent) writes a spec with one `.cluster-smoke` job
per lab, and a `trigger` job runs it, so every lab is its own parallel GitLab job.

WHICH labs:
  * `SMOKE_ALL=true` env     → every lab that has a smoke plan, on EVERY pipeline
                              (global override, mirrors BUILD_ALL for image builds; set
                              as a CI/CD variable to always run the full smoke for testing)
  * `--all`                     → every lab that has a smoke plan (scheduled/manual full runs)
  * otherwise (default)         → the labs whose files changed vs the MR base, exactly the
                                  workshops `changed.py` reports. If the shared harness or a
                                  plan changed, `changed.py` already falls back to ALL labs.
  * `--only <lab> [<lab> ...]`  → an explicit, fixed list (ad-hoc / debugging)

Every generated job extends a `.cluster-smoke` hidden template defined in the spec:
oc-login in `before_script`, `--no-links --ref <branch> --throwaway` smoke invocation in
`script`. `--throwaway` (MR mode) deploys a throwaway Workshop hidden from the portal that
pulls content from the source branch, never touching the Argo-managed catalog Workshops.

Usage (run in `test/ci/`):
    python3 test/ci/gen-smoke-child.py child-smoke.yml [--all|--only lab ...]
"""

import argparse
import os
import pathlib
import subprocess
import sys

REPO = pathlib.Path(subprocess.run(["git", "rev-parse", "--show-toplevel"],
                                   capture_output=True, text=True).stdout.strip() or ".")
PLANS = REPO / "test" / "workshops" / "smoke-plans"

# Hidden template embedded in the generated spec. One `before_script` (oc-login, idempotent,
# same variables as the old .cluster block) and one `script` shared by every lab job; each job
# supplies only its lab name via the LAB variable. The CI/CD smoke variables are resolved by
# the generator into the spec's `variables:` (a child pipeline does NOT inherit the parent's
# top-level `variables:`), so the child is self-contained.
TEMPLATE = """\
# Auto-generated by test/ci/gen-smoke-child.py — do not edit by hand.
# One job per lab so cluster smoke runs in parallel instead of one long serial job.
stages:
  - smoke

variables:
  CI_BASE_IMAGE: {ci_base_image}
  SMOKE_REF: "{smoke_ref}"
  SMOKE_THROWAWAY: "{smoke_throwaway}"

.cluster-smoke:
  stage: smoke
  image:
    name: $CI_BASE_IMAGE
    pull_policy: [always, if-not-present]
  needs: []
  before_script:
    # Log into the dev OpenShift cluster so smoke_test.py can drive `oc`. Idempotent. Fails
    # loudly if CI_OC_HOST / CI_OC_TOKEN are unset (masked + protected project variables).
    - |
      if [ -z "${{CI_OC_HOST:-}}" ] || [ -z "${{CI_OC_TOKEN:-}}" ]; then
        echo "ERROR: CI_OC_HOST and CI_OC_TOKEN must be set for cluster-tier jobs."
        exit 1
      fi
      if oc whoami >/dev/null 2>&1; then
        echo "[oc] already logged in as $(oc whoami) to ${{CI_OC_HOST}}."
      else
        echo "[oc] logging into ${{CI_OC_HOST}}..."
        OC_LOGIN_ARGS=(login "${{CI_OC_HOST}}" --token="${{CI_OC_TOKEN}}")
        [ -n "${{CA_BUNDLE:-}}" ] && OC_LOGIN_ARGS+=(--certificate-authority="${{CA_BUNDLE}}")
        [ -n "${{CI_OC_CA_BUNDLE:-}}" ] && OC_LOGIN_ARGS+=(--certificate-authority="${{CI_OC_CA_BUNDLE}}")
        [ "${{CI_OC_INSECURE:-}}" = "true" ] && OC_LOGIN_ARGS+=(--insecure-skip-tls-verify=true)
        [ -n "${{CI_OC_CONTEXT:-}}" ] && OC_LOGIN_ARGS+=(--context="${{CI_OC_CONTEXT}}")
        [ -n "${{CI_OC_USERNAME:-}}" ] && OC_LOGIN_ARGS+=(--username="${{CI_OC_USERNAME}}")
        if ! oc "${{OC_LOGIN_ARGS[@]}}"; then
          echo "[oc] ERROR: login to ${{CI_OC_HOST}} failed — check CI_OC_TOKEN."
          exit 1
        fi
        echo "[oc] logged in as $(oc whoami)."
      fi
  script:
    # SMOKE_ARGS mirrors the old run-workshops.sh --smoke flags: no re-link-check of the
    # markdown (the fast tier already did labels/links/coverage), pull content from the MR
    # source branch, deploy a portal-hidden throwaway Workshop.
    - SMOKE_ARGS="--no-links"
    - if [ -n "${{SMOKE_REF:-}}" ]; then SMOKE_ARGS="$SMOKE_ARGS --ref ${{SMOKE_REF}}"; fi
    - if [ "${{SMOKE_THROWAWAY:-}}" = "1" ]; then SMOKE_ARGS="$SMOKE_ARGS --throwaway"; fi
    - test -n "${{LAB:-}}" || {{ echo "LAB unset — internal error in generated child spec"; exit 1; }}
    - python3 test/workshops/smoke_test.py "$LAB" $SMOKE_ARGS
{lab_jobs}
"""

LAB_JOB = """\
{lab}:
  extends: .cluster-smoke
  variables:
    LAB: {lab}
"""


def all_labs():
    """Every lab that has a smoke plan, sorted."""
    if not PLANS.is_dir():
        return []
    return sorted(p.stem for p in PLANS.glob("*.json"))


def changed_labs():
    """The labs changed vs the base, as reported by changed.py (space-separated WORKSHOPS=)."""
    r = subprocess.run([sys.executable, str(REPO / "test" / "ci" / "changed.py")],
                       capture_output=True, text=True, cwd=str(REPO))
    for line in r.stdout.splitlines():
        if line.startswith("WORKSHOPS="):
            value = line.split("=", 1)[1].strip().strip('"')
            return value.split() if value else []
    return []


def select_labs(args):
    # Global override: SMOKE_ALL=true CI/CD var forces the full smoke on every
    # pipeline (mirrors BUILD_ALL for image builds). Handy for testing.
    if os.environ.get("SMOKE_ALL", "").lower() == "true":
        return all_labs(), "SMOKE_ALL=true — run full smoke on every pipeline"

    if args.all:
        return all_labs(), "all labs with a smoke plan"
    if args.only:
        known = set(all_labs())
        return [l for l in args.only if l in known], f"explicit --only list ({', '.join(args.only)})"

    changed = changed_labs()
    if changed:
        # Restrict to labs that actually have a plan to run.
        known = set(all_labs())
        labs = [l for l in changed if l in known]
        return labs, "labs changed since the MR base"
    # changed.py reported nothing (no base ref, e.g. scheduled/branch push) → full set.
    return all_labs(), "no MR diff base — fallback to ALL labs"


def resolve_vars():
    """Resolve the smoke CI variables into values the CHILD pipeline can use.

    A child pipeline does not inherit the parent's top-level `variables:`, so the generator
    (which runs inside the parent) reads them from its own environment and bakes the result in.
    """
    ci_base_image = os.environ.get("CI_BASE_IMAGE", "ghcr.io/rummens/dcs-ci:dev")
    smoke_ref = os.environ.get(
        "SMOKE_REF",
        os.environ.get("CI_MERGE_REQUEST_SOURCE_BRANCH_NAME") or
        os.environ.get("CI_COMMIT_BRANCH") or "")
    smoke_throwaway = os.environ.get("SMOKE_THROWAWAY", "1")
    return ci_base_image, smoke_ref, smoke_throwaway


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("out", help="path to write the generated child spec")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--all", action="store_true", help="every lab with a smoke plan")
    g.add_argument("--only", nargs="+", help="explicit lab list (ad-hoc)")
    args = p.parse_args()

    labs, why = select_labs(args)
    if not labs:
        print(f"gen-smoke-child: nothing to run ({why}). Empty child spec.", file=sys.stderr)
        # An empty child pipeline is still valid; emit a single no-op job so the trigger
        # does not error on a spec with no jobs. The generated noop job is not an error to
        # the `strategy: depend` trigger — the child reports success.
        write_empty(args.out)
        print(f"gen-smoke-child: wrote no-op child spec -> {args.out}")
        return 0

    ci_base_image, smoke_ref, smoke_throwaway = resolve_vars()
    lab_jobs = "\n\n".join(LAB_JOB.format(lab=l) for l in labs)
    spec = TEMPLATE.format(ci_base_image=ci_base_image, smoke_ref=smoke_ref,
                           smoke_throwaway=smoke_throwaway, lab_jobs=lab_jobs)
    pathlib.Path(args.out).write_text(spec + "\n")
    # keep it out of git (it is generated per-pipeline)
    print(f"gen-smoke-child: {len(labs)} lab job(s) ({why}) -> {args.out}")
    print(f"                 smoke ref: {smoke_ref or '(default)'}  throwaway: {smoke_throwaway}")


def write_empty(out):
    """Emit an (empty) valid spec when there is nothing to run."""
    spec = "stages:\n  - smoke\n\nnoop:\n  stage: smoke\n  script:\n    - echo nothing-to-run\n"
    pathlib.Path(out).write_text(spec)


if __name__ == "__main__":
    main()