{{- if .Values.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.educates.installer.namespace }}
  labels:
    {{- include "educates.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
{{- end }}
